### ISSUE TITLE
PQ staging deployment issue

### ISSUE THREAD

**Issue by lukaszraczylo** [ministryofjustice/cloud-platform#499]
User Daniel P. has informed us that staging environment site is inaccessible after successful deployment.

**Comment by lukaszraczylo** [comment]
After checking the state of containers it turns out that staging environment used library/parliamentaryquestions as a part of the docker image path while image still being built and pushed into the path without "library" prefix.

**Comment by lukaszraczylo** [comment]
DATABASE_URL is set, yet it's missing database username variable. Investigating now.

**Comment by lukaszraczylo** [comment]
Issue above was related to running fab update with wrong parameters and not including secrets file. It's been sorted, yet the slow application issue is related to the application code itself:

```
I, [2018-11-14T15:09:32.406234 #273]  INFO -- : Refreshing Gem list
E, [2018-11-14T15:09:34.496439 #260] ERROR -- : uninitialized constant LogStuff
Did you mean?  LogStash (NameError)
/usr/src/app/config/environment.rb:8:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `eval'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `block in builder'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:795:in `build_app!'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:660:in `init_worker_process'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:682:in `worker_loop'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:563:in `maintain_worker_count'
/usr/local/bundle/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:293:in `join'
/usr/local/bundle/gems/unicorn-5.4.1/bin/unicorn:126:in `<top (required)>'
/usr/local/bundle/bin/unicorn:17:in `load'
/usr/local/bundle/bin/unicorn:17:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/src/app/bin/bundle:3:in `load'
/usr/src/app/bin/bundle:3:in `<main>'
E, [2018-11-14T15:09:34.557860 #27] ERROR -- : reaped #<Process::Status: pid 260 exit 1> worker=3
I, [2018-11-14T15:09:34.566548 #276]  INFO -- : Refreshing Gem list
```

**Comment by lukaszraczylo** [comment]
Issue related to the application itself as per thread and David's advice. https://mojdt.slack.com/archives/C57UPMZLY/p1542190599099500
