### ISSUE TITLE
Integration tests: bug fix: suite timeout

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#5192]
## Background

Occasionally, the int test suite will timeout. Fail fast or fix the cause of the timeout.

```
  Timeline >>

  [FAILED] in [It] - /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:119 @ 01/16/24 09:28:31.358


  Attempt #1 Failed.  Retrying ↺ @ 01/16/24 09:28:32.03


  [TIMEDOUT] in [BeforeEach] - /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:78 @ 01/16/24 09:28:59.344

  << Timeline


  [TIMEDOUT] A suite timeout occurred

  In [BeforeEach] at: /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:78 @ 01/16/24 09:28:59.344


  Full Stack Trace


  This is the Progress Report generated when the suite timeout occurred:

    cert-manager when the namespace has a certificate resource should succeed and present a staging certificate (Spec Runtime: 23m29.032s)

      /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:114

      In [BeforeEach] (Node Runtime: 27.314s)

        /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:78


      Spec Goroutine

      goroutine 143 [sleep]

        time.Sleep(0x4a817c800)

          /usr/local/go/src/runtime/time.go:195

        github.com/gruntwork-io/terratest/modules/retry.DoWithRetryInterfaceE({0x7f16a1934588, 0xc0006c10e0}, {0xc000f84000, 0x3c}, 0x1e, 0x40?, 0xc000999970)

          /root/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.8/modules/retry/retry.go:104

        github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE({0x7f16a1934588, 0xc0006c10e0}, {0xc000f84000, 0x3c}, 0x4ae969?, 0xc000999a10?, 0xc000999a78)

          /root/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.8/modules/retry/retry.go:68

        github.com/gruntwork-io/terratest/modules/retry.DoWithRetry({0x7f16a1934588, 0xc0006c10e0}, {0xc000f84000, 0x3c}, 0x1?, 0x2beae18?, 0x2beae10?)

          /root/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.8/modules/retry/retry.go:57

        github.com/gruntwork-io/terratest/modules/k8s.WaitUntilIngressAvailable({0x7f16a1934588, 0xc0006c10e0}, 0xc0000b2140, {0x2ad6e27, 0x18}, 0xc000cd0270?, 0x0?)

          /root/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.8/modules/k8s/ingress.go:67

      > github.com/ministryofjustice/cloud-platform-infrastructure/test/helpers.CreateHelloWorldApp(0xc000999d58, 0x2ad8619?)

          /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/helpers/deploy.go:49

            | 	}

            | 

            > 	k8s.WaitUntilIngressAvailable(GinkgoT(), opt, "integration-test-app-ing", app.IngressRetryCount, 20*time.Second)

            | 	return nil

            | }

      > github.com/ministryofjustice/cloud-platform-infrastructure/test.glob..func2.1.1()

          /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:102

            | }

            | 

            > err = helpers.CreateHelloWorldApp(&app, options)

            | Expect(err).NotTo(HaveOccurred())

            | 

        github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x2c12, 0xc000de61e0})

          /root/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.2/internal/node.go:463

        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()

          /root/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.2/internal/suite.go:889

        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 36

          /root/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.2/internal/suite.go:876


      Goroutines of Interest

      goroutine 1 [chan receive, 25 minutes]

        testing.(*T).Run(0xc000b88820, {0x2abe016, 0x8}, 0x2bea118)

          /usr/local/go/src/testing/testing.go:1649

        testing.runTests.func1(0x0?)

          /usr/local/go/src/testing/testing.go:2054

        testing.tRunner(0xc000b88820, 0xc0000ff878)

          /usr/local/go/src/testing/testing.go:1595

        testing.runTests(0xc00061e640?, {0x4dbf490, 0x1, 0x1}, {0x47e240?, 0xc0000ff8bf?, 0x0?})

          /usr/local/go/src/testing/testing.go:2052

        testing.(*M).Run(0xc00061e640)

          /usr/local/go/src/testing/testing.go:1925

      > github.com/ministryofjustice/cloud-platform-infrastructure/test.TestMain(0xae3beea76d60b97f?)

          /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/platform_test.go:59

            | // Run tests

            | fmt.Printf("Starting tests on cluster: %s\n", c.ClusterName)

            > exitVal := m.Run()

            | 

            | // Cleanup all prefixed namespaces after the tests have finished.

        main.main()

          _testmain.go:49


  There were additional failures detected.  To view them in detail run ginkgo -vv

------------------------------


Summarizing 1 Failure:

  [TIMEDOUT] cert-manager when the namespace has a certificate resource [BeforeEach] should succeed and present a staging certificate

  /tmp/build/12223d70/cloud-platform-infrastructure-repo/test/certmanager_test.go:78


Ran 89 of 107 Specs in 1501.325 seconds

FAIL! - Suite Timeout Elapsed -- 88 Passed | 1 Failed | 0 Pending | 18 Skipped
```

## Definition of done

- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Reducing timeout here seems to allow the certman test to fail and flaky retry now succeeds
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/test/certmanager_test.go#L119

https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/2563#L65bb652e:1192

**Comment by sj-williams** [comment]
Update:

certman test has since failed again. Ex:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/2588#L65bb7686:2583

Will need some further investigation to understand why flaky tests are not always executing in the event of a test failure.

**Comment by Matt-Alinosn** [comment]
Agrred to close in Planning 21/2/24 and will raise new ticket is bug reappears
