### ISSUE TITLE
Fab update - PVB Deploy

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#557]
## Service name

Prison Visits Booking

## Service environment

- [ ] Dev / Development
- [x] Staging
- [Maybe] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Cannot update config for PVB2 (staging)

## Problem description

Error occurs when doing a fab update for pvb2-deploy (repo: https://github.com/ministryofjustice/pvb2-deploy/). 

```
[52.212.148.110] out: --------------
[52.212.148.110] out: Succeeded: 255 (changed=6)
[52.212.148.110] out: Failed:      1
[52.212.148.110] out: --------------
[52.212.148.110] out: Total states run:     256
[52.212.148.110] out: [ERROR   ] An un-handled exception was caught by salt's global exception handler:
[52.212.148.110] out: SaltStateError: State did not execute successfully
[52.212.148.110] out: Traceback (most recent call last):
[52.212.148.110] out:   File "/usr/local/bin/salt_utils_state.py", line 126, in <module>
[52.212.148.110] out:     salt_utils_state_wrapper.state(args.state)
[52.212.148.110] out:   File "/usr/local/bin/salt_utils_state.py", line 66, in state
[52.212.148.110] out:     return self.check_state_result(result)
[52.212.148.110] out:   File "/usr/local/bin/salt_utils_state.py", line 92, in check_state_result
[52.212.148.110] out:     raise SaltStateError('State did not execute successfully')
[52.212.148.110] out: SaltStateError: State did not execute successfully
[52.212.148.110] out: Traceback (most recent call last):
[52.212.148.110] out:   File "/usr/local/bin/salt_utils_state.py", line 126, in <module>
[52.212.148.110] out:     salt_utils_state_wrapper.state(args.state)
[52.212.148.110] out:   File "/usr/local/bin/salt_utils_state.py", line 66, in state
[52.212.148.110] out:     return self.check_state_result(result)
[52.212.148.110] out:   File "/usr/local/bin/salt_utils_state.py", line 92, in check_state_result
[52.212.148.110] out:     raise SaltStateError('State did not execute successfully')
[52.212.148.110] out: __main__.SaltStateError: State did not execute successfully
[52.212.148.110] out: CRITICAL:bootstrap-salt::salt_utils:There was a problem running the salt state...aborting.
[52.212.148.110] out:


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: /usr/local/bin/salt_utils.py -s highstate
Executed: sudo -S -p 'sudo password:'  /usr/local/bin/salt_utils.py -s highstate

Aborting.

Fatal error: One or more hosts failed while executing task 'run_highstate'

Aborting.
Disconnecting from 52.212.148.110... done.
```

## Contact person

Toby Retallick

**Comment by lukaszraczylo** [comment]
Hi Toby,
Issue caused by one of the github users. I've updated ssh keys users for those and managed to run the successful update on staging. 

Ps. This issue has not affected your ability to deploy or apply changes before the update so there's nothing to be worried about :)
