### ISSUE TITLE
Intermittent RDS connection errors

### ISSUE THREAD

**Issue by townxelliot** [ministryofjustice/cloud-platform#6291]
## Service name

rd-ai-nexus-dev

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

This service is currently in development, and we are using the Cloud Platform deployment for testing with users. However, the high rate of errors makes these demos less useful, more erratic, and creates a poor impression with users.

## Problem description

We see occasional errors like this in the application pod logs:

```
[2024-10-15 08:12:32,727] - ERROR: Exception on /admin/servicearea/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pg8000/core.py", line 144, in _flush
    sock.flush()
  File "/usr/local/lib/python3.9/socket.py", line 734, in write
    return self._sock.send(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1207, in send
    return self._sslobj.write(data)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/pg8000/legacy.py", line 248, in execute
    self._c.execute_simple("begin transaction")
  File "/usr/local/lib/python3.9/site-packages/pg8000/core.py", line 685, in execute_simple
    _flush(self._sock)
  File "/usr/local/lib/python3.9/site-packages/pg8000/core.py", line 146, in _flush
    raise InterfaceError("network error") from e
pg8000.exceptions.InterfaceError: network error
```

Some of the time, the database connection is made successfully and there is no error. Around 25% of the time (there doesn't really seem to be a pattern, though) we see the above error.

The tables involved are very small so this is highly unlikely to be due to the query timing out.

It might be that our RDS setup is not tuned correctly, so any guidance on that would be welcome: https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/rd-ai-nexus-dev/resources/rds-postgresql.tf

## Contact person

research-and-development@justice.gov.uk

**Comment by sj-williams** [comment]
No obvious issues with the RDS instance via looking at metrics/logs

User looking at the python PG connector library and considering testing a different implementation

**Comment by sj-williams** [comment]
Issue appears to have been resolved by switching from `pg8000` DB driver to `psycopg`.

Closing ticket.
