### ISSUE TITLE
Fab update in Template Deploy Jump image

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#881]
## Service name

Prison Visits Booking
## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Two developers cannot run fab commands inside the Template Deploy Jump image

## Problem description

Affected users:
- Kath Pobee-Norris
- Me (Toby Retallick)

When Kath and I try to run a fab command inside the image we receive an AWS Zone ID error. It appears the id is initially found but then a change occurs and then it is 'not found'.

```
INFO:root:bootstrap-cfn:: Validating default settings for environment staging in file /usr/local/lib/python2.7/site-packages/bootstrap_cfn/config_defaults.yaml
INFO:root:bootstrap-cfn:: Validating user settings for environment staging in file ./cloudformation/pvb2.yaml
INFO:root:bootstrap-cfn:: Validating passwords settings for environment staging in file ./cloudformation/pvb2-secrets.yaml
INFO:bootstrap-cfn:fab_tasks::get_zone_id: Found master zone 'dsd.io' in config...
INFO:root:bootstrap-cfn:: Validating default settings for environment staging in file /usr/local/lib/python2.7/site-packages/bootstrap_cfn/config_defaults.yaml
INFO:root:bootstrap-cfn:: Validating user settings for environment staging in file ./cloudformation/pvb2.yaml
INFO:root:bootstrap-cfn:: Validating passwords settings for environment staging in file ./cloudformation/pvb2-secrets.yaml
INFO:bootstrap-cfn:fab_tasks::get_zone_id: Found master zone 'dsd.io' in config...
[ERROR] ZoneIDNotFoundError: Could not find a zone id for zone name 'dsd.io'.Please check that this hosted zone exists and is in the account you've specified
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/deploy/fabfile.py", line 103, in update
    vendor_upload()
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 170, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/deploy/fabfile.py", line 72, in vendor_upload
    salt.upload_salt()
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 170, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bootstrap_salt/fab_tasks.py", line 295, in upload_salt
    stack_name = get_stack_name()
  File "/usr/local/lib/python2.7/site-packages/bootstrap_cfn/fab_tasks.py", line 414, in get_stack_name
    zone_id = get_zone_id()
  File "/usr/local/lib/python2.7/site-packages/bootstrap_cfn/fab_tasks.py", line 497, in get_zone_id
    raise ZoneIDNotFoundError(zone_name)
bootstrap_cfn.errors.ZoneIDNotFoundError: Could not find a zone id for zone name 'dsd.io'.Please check that this hosted zone exists and is in the account you've specified
```

The other developer on the team does not experience this error however (Ross Jones). We have checked each other's commands and config and they are exactly the same. 

We wonder if there is an IAM permissions issue affecting Kath and my accounts? Ross's access was only granted this week (by Igor in Prisoner Money) so perhaps there are some differences we are unaware of. 

The only noticeable difference is that when Kath and I log into the aws console we go to the Ireland region by default, Ross goes to London. We have tried configuring the aws cli to use both eu-west-1 and eu-west-2 and this has made no difference

## Contact person

Toby Retallick

**Comment by lukaszraczylo** [comment]
The issue is caused by incorrect AWS credentials setup - please verify that your IAM user keys are still active and / or generate new set for the mentioned account you're trying to access. Route53 is zone independent so eu-west-1 or eu-west-2 wouldn't make a difference.
